version: '3.8'

services:
  governance-analytics-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: governance-analytics-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=${NODE_ENV:-development}
      - JWT_SECRET=${JWT_SECRET}
      - SNAPSHOT_API_KEY=${SNAPSHOT_API_KEY}
      - TALLY_API_KEY=${TALLY_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - USE_MOCK_DATA=${USE_MOCK_DATA:-true}
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - dao-analytics-network

networks:
  dao-analytics-network:
    driver: bridge 