version: '3.8'

services:
  governance-analytics-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: governance-analytics-api-dev
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
      - SNAPSHOT_API_KEY=${SNAPSHOT_API_KEY}
      - TALLY_API_KEY=${TALLY_API_KEY}
      - LOG_LEVEL=debug
      - USE_MOCK_DATA=true
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - dao-analytics-network

networks:
  dao-analytics-network:
    driver: bridge 